# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ljaeck/Code/JuceProjects/AudioPlugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ljaeck/Code/JuceProjects/AudioPlugin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ljaeck/Code/JuceProjects/AudioPlugin/CMakeFiles /home/ljaeck/Code/JuceProjects/AudioPlugin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ljaeck/Code/JuceProjects/AudioPlugin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ljaeck/Code/JuceProjects/AudioPlugin/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AudioPluginExample

# Build rule for target.
AudioPluginExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AudioPluginExample
.PHONY : AudioPluginExample

# fast build rule for target.
AudioPluginExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/build
.PHONY : AudioPluginExample/fast

#=============================================================================
# Target rules for targets named AudioPluginExample_All

# Build rule for target.
AudioPluginExample_All: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AudioPluginExample_All
.PHONY : AudioPluginExample_All

# fast build rule for target.
AudioPluginExample_All/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_All.dir/build.make CMakeFiles/AudioPluginExample_All.dir/build
.PHONY : AudioPluginExample_All/fast

#=============================================================================
# Target rules for targets named AudioPluginExample_Standalone

# Build rule for target.
AudioPluginExample_Standalone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AudioPluginExample_Standalone
.PHONY : AudioPluginExample_Standalone

# fast build rule for target.
AudioPluginExample_Standalone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/build
.PHONY : AudioPluginExample_Standalone/fast

#=============================================================================
# Target rules for targets named AudioPluginExample_VST3

# Build rule for target.
AudioPluginExample_VST3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AudioPluginExample_VST3
.PHONY : AudioPluginExample_VST3

# fast build rule for target.
AudioPluginExample_VST3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/build
.PHONY : AudioPluginExample_VST3/fast

#=============================================================================
# Target rules for targets named juce_vst3_helper

# Build rule for target.
juce_vst3_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juce_vst3_helper
.PHONY : juce_vst3_helper

# fast build rule for target.
juce_vst3_helper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/build
.PHONY : juce_vst3_helper/fast

PluginEditor.o: PluginEditor.cpp.o
.PHONY : PluginEditor.o

# target to build an object file
PluginEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginEditor.cpp.o
.PHONY : PluginEditor.cpp.o

PluginEditor.i: PluginEditor.cpp.i
.PHONY : PluginEditor.i

# target to preprocess a source file
PluginEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginEditor.cpp.i
.PHONY : PluginEditor.cpp.i

PluginEditor.s: PluginEditor.cpp.s
.PHONY : PluginEditor.s

# target to generate assembly for a file
PluginEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginEditor.cpp.s
.PHONY : PluginEditor.cpp.s

PluginProcessor.o: PluginProcessor.cpp.o
.PHONY : PluginProcessor.o

# target to build an object file
PluginProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginProcessor.cpp.o
.PHONY : PluginProcessor.cpp.o

PluginProcessor.i: PluginProcessor.cpp.i
.PHONY : PluginProcessor.i

# target to preprocess a source file
PluginProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginProcessor.cpp.i
.PHONY : PluginProcessor.cpp.i

PluginProcessor.s: PluginProcessor.cpp.s
.PHONY : PluginProcessor.s

# target to generate assembly for a file
PluginProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/PluginProcessor.cpp.s
.PHONY : PluginProcessor.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_Standalone.dir/build.make CMakeFiles/AudioPluginExample_Standalone.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample_VST3.dir/build.make CMakeFiles/AudioPluginExample_VST3.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.cpp.s

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.o: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.o
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.o

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.i: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.i
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.i

home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.s: home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AudioPluginExample.dir/build.make CMakeFiles/AudioPluginExample.dir/home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.s
.PHONY : home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AudioPluginExample_All"
	@echo "... AudioPluginExample"
	@echo "... AudioPluginExample_Standalone"
	@echo "... AudioPluginExample_VST3"
	@echo "... juce_vst3_helper"
	@echo "... PluginEditor.o"
	@echo "... PluginEditor.i"
	@echo "... PluginEditor.s"
	@echo "... PluginProcessor.o"
	@echo "... PluginProcessor.i"
	@echo "... PluginProcessor.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_ara.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_core/juce_core.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_data_structures/juce_data_structures.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_events/juce_events.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_graphics/juce_graphics.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... home/ljaeck/JUCE/include/JUCE-7.0.9/modules/juce_gui_extra/juce_gui_extra.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ljaeck/Code/JuceProjects/AudioPlugin/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

